using System;
using System.Collections.Generic;
using ivend.Models;

namespace ivend.Services
{
  class IvendService
  {
    //object to hold data
    private Machine Machine { get; set; } = new Machine();
    ///<summary> collection of messages generated by the service to be drawn to the console by the controller</summary>
    public List<string> Messages = new List<string>();
    public void PrintItems()
    {
      Messages.Add("--Vending Maching Items--");
      Messages.Add($"Credit: {Machine.Credit:c}\n");
      for (int i = 0; i < Machine.ItemList.Count; i++)
      {
        string item = Machine.ItemList[i].GetVendingMachineItem();
        Messages.Add($"{i + 1}.) {item}");
      }
      Messages.Add("\npress (d) to insert dime or (q) to quit");
    }

    public void IncreaseCredit(char coin)
    {
      switch (coin)
      {
        case 'd':
          Machine.Credit += 0.10f;
          break;
      }
    }
  }
}