using System;
using System.Collections.Generic;
using ivend.Models;

namespace ivend.Services
{
  class IvendService
  {
    //object to hold data
    private Machine Machine { get; set; } = new Machine();
    ///<summary> collection of messages generated by the service to be drawn to the console by the controller</summary>
    public List<string> Messages = new List<string>();
    public void PrintItems()
    {
      for (int i = 0; i < Machine.ItemList.Count; i++)
      {
        string item = Machine.ItemList[i].GetVendingMachineItem();
        Messages.Add($"{i + 1}.) {item}");
      }
    }
  }
}